version: '3.9'

services:
  db:
    image: postgres:15
    container_name: school_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: studentportal
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: studentportal_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/studentportal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
